### PR TITLE
Address go vet issues

### PR DESCRIPTION
**Pull request by StevenMaude**
### What

Make closing HTTP responses more robust.

Without this commit, an error can result in an attempt to access a nil response.

### How to review

Ensure the retrieve-dataset-taxonomy still behaves as expected. 

### Who can review

Anyone who uses that code.

### CODE REVIEW

**Comment by StevenMaude** [comment]
`go vet` also complained about some of the struct tags.

```
# github.com/ONSdigital/dp-census-dataset-search-api/scripts/retrieve-dataset-taxonomy
scripts/retrieve-dataset-taxonomy/main.go:110:2: struct field tag `json:"theme` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
scripts/retrieve-dataset-taxonomy/main.go:114:2: struct field tag `json:"uri` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
scripts/retrieve-dataset-taxonomy/main.go:145:2: struct field tag `json:"uri` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
```

Not sure if there's some special reason why they're the way they are, so have left them. Feel free to include the diff below, or I can push what I have if you prefer.

```diff
diff --git a/scripts/retrieve-dataset-taxonomy/main.go b/scripts/retrieve-dataset-taxonomy/main.go
index 6621782..9ccae8d 100644
--- a/scripts/retrieve-dataset-taxonomy/main.go
+++ b/scripts/retrieve-dataset-taxonomy/main.go
@@ -107,11 +107,11 @@ type TopTaxonomy struct {
 }
 
 type Section struct {
-       Theme Theme `json:"theme`
+       Theme Theme `json:"theme"`
 }
 
 type Theme struct {
-       URI string `json:"uri`
+       URI string `json:"uri"`
 }
 
 func CreateFirstLevelTaxonomy(ctx context.Context, reader io.Reader) (*TopTaxonomy, error) {
@@ -142,7 +142,7 @@ type Description struct {
 }
 
 type ChildSection struct {
-       URI string `json:"uri`
+       URI string `json:"uri"`
 }
 
 func GetTopics(ctx context.Context, url, parentTopic string, level int) (*models.Topic, error) {
```

**Comment by nshumoogum** [comment]
Hi Steven

the `defer resp.Body.Close()` should take place after error is checked 👍 . Secondly if you would correct the json tags in structs with the missing double quotes I will accept pull request.

**Review by nshumoogum — APPROVED** [review]
Thanks

**Comment by StevenMaude** [comment]
@nshumoogum Thanks for taking a look!

Only other possible thing `go vet` complains about is the `Asset` in `internal/elasticsearch`assets.go` if you don't run `go generate` first :slightly_smiling_face:

**Comment by nshumoogum** [comment]
> @nshumoogum Thanks for taking a look!
> 
> Only other possible thing `go vet` complains about is the `Asset` in `internal/elasticsearch`assets.go`if you don't run`go generate` first 🙂

I would not commit assets as these are generated from code, the README.md describes how the api should be run, using `make debug` which runs go generate.

If someone didn't want to use the setup described in the README.md then they are on their own to realise that they will need to generate the assets using `go generate ./..`, I would expect them to investigate the Makefile to see what commands were needed to be run.

**Comment by StevenMaude** [comment]
(To clarify: I meant everything was now effectively clear on the codebase when running `go vet`, not that there was anything more to address. The only thing that *could* be flagged by `go vet` is a non-issue :+1:)

**Pull request merged**
